version: '3'

services:
  consul:
      image: consul:0.9.3
      ports:
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
  redis:
      image: redis
      ports:
        - "6379:6379"
#  zookeeper:
#      image: jplock/zookeeper
#      ports:
#        - "2181:2181"
#        - "2888:2888"
#        - "3888:3888"
  mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: spring_cloud
  zipkin:
      image: openzipkin/zipkin:1.31.0
      ports:
        - "9411:9411"